name: bazel (bento) arm64

on:
  workflow_dispatch:

jobs:

  build:
    runs-on:
    - self-hosted
    - "os=linux"
    - "arch=arm64"
    - "engflow-cluster=local"
    - "engflow-bento-name=mybento"
    - "engflow-bento-allow-save=true"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Run bazel
      run: |
        bazel info
